# R10.7 -- eliminate prose dashes. Assert-guarded: exact unique match or abort.
# Numeric en-dash ranges (0.70--0.90, 31001--31020) are deliberately preserved.
import sys
s = open('main.tex', encoding='utf-8', newline='').read()
E = []
def rep(old, new, tag):
    global s
    if s.count(old) != 1:
        E.append((tag, s.count(old))); return
    s = s.replace(old, new); print("OK  ", tag)

R = [
("instead -- a different mechanism from the",
 "instead, a different mechanism from the", "115"),
("mechanism class -- an exact-match lookup, a fuzzy\nretrieval index, a trained model -- before any",
 "mechanism class (an exact-match lookup, a fuzzy\nretrieval index, a trained model) before any", "138"),
("statistic --\nhistorical label consistency -- actually",
 "statistic,\nhistorical label consistency, actually", "144"),
("mechanism -- an exact lookup against history -- should suffice",
 "mechanism, an exact lookup against history, should suffice", "190"),
("Two lexical conditions -- CLEAN", "Two lexical conditions, CLEAN", "207a"),
("perturbation) -- are crossed", "perturbation), are crossed", "207b"),
("selects the right mechanism -- it is a bounded",
 "selects the right mechanism. It is a bounded", "257"),
("|$ -- the identical closed-form", "|$, the identical closed-form", "309"),
("processing workflow -- the closest", "processing workflow, the closest", "347"),
("combinatorial pipeline space -- a difference in kind, not a claim of\nsuperiority.",
 "combinatorial pipeline space, a difference in kind rather than a claim of\nsuperiority.", "351"),
("decision -- the opposite temporal", "decision, the opposite temporal", "364"),
("experiment reported here -- the LLM mechanism is explicitly excluded from\nExperiment~1 (Section~7.3) -- and both",
 "experiment reported here (the LLM mechanism is explicitly excluded from\nExperiment~1, Section~7.3), and both", "411"),
("per-company models --\nthe same phenomenon", "per-company models,\nthe same phenomenon", "427"),
("from an item -- a \"product\" --\nto a label -- an \"account\" -- together with",
 "from an item (a \"product\")\nto a label (an \"account\"), together with", "481"),
("for this mechanism -- matching", "for this mechanism: matching", "538"),
("Coverage -- the share of test items for which the\nmechanism does not abstain -- is below",
 "Coverage, the share of test items for which the\nmechanism does not abstain, is below", "541"),
("for every test item -- not as a\nfallback", "for every test item, rather than as a\nfallback", "556"),
("of the 240 conditions -- this mechanism never abstains",
 "of the 240 conditions: this mechanism never abstains", "561"),
("cannot observe -- which is", "cannot observe, which is", "584"),
("Cross-company alignment -- the rate at\nwhich different companies agree on a shared product's dominant account -- is\nfixed at 0.695 -- the production-observed value, cited from a confidential\nengagement and not independently reproducible from this repository -- so\nthat it does not become",
 "Cross-company alignment, the rate at\nwhich different companies agree on a shared product's dominant account, is\nfixed at 0.695 (the production-observed value, cited from a confidential\nengagement and not independently reproducible from this repository), so\nthat it does not become", "621"),
("ADS -- the measured, train-only share", "ADS: the measured, train-only share", "652"),
("perturbable surface string -- this\nis confirmed", "perturbable surface string. This\nis confirmed", "665"),
("lexical perturbation -- the existing generator's",
 "lexical perturbation, the existing generator's", "680"),
("for this generator -- not a general claim", "for this generator, rather than a general claim", "687"),
("criterion -- whether the top fuzzy match resolves to the same underlying\nproduct as the query, not whether the resulting account label is correct --\nsubject",
 "criterion (whether the top fuzzy match resolves to the same underlying\nproduct as the query, rather than whether the resulting account label is\ncorrect), subject", "720"),
("lines -- a paired, not an independent, comparison.",
 "lines: a paired rather than an independent comparison.", "757"),
("comparison -- excluding ties", "comparison, excluding ties", "795"),
("rule R3 -- so named", "rule R3, so named", "803a"),
("taxonomy, not an alternative considered within this\nexperiment -- is reused",
 "taxonomy rather than an alternative considered within this\nexperiment, is reused", "803b"),
("seeds per target -- using no import of, and no reference to, either\nmechanism's code -- to characterize",
 "seeds per target (using no import of, and no reference to, either\nmechanism's code) to characterize", "821"),
("performance level --\nit says nothing yet", "performance level. It says nothing yet", "948"),
("all 120 of 120 conditions -- exceptionless,\nunconditional",
 "all 120 of 120 conditions, exceptionless and\nunconditional", "971"),
("in all 120 of 120 conditions --\nalso exceptionless (Figure", "in all 120 of 120 conditions, also\nexceptionless (Figure", "973"),
("R3's own thresholds -- the primary framing, matching the locked\nwording this paper draws on -- R3 agrees",
 "R3's own thresholds (the primary framing, matching the locked\nwording this paper draws on), R3 agrees", "1004"),
("baseline -- not significant at", "baseline, which is not significant at", "1020"),
("(Section~5.6) -- not a single moderate effect, and reporting",
 "(Section~5.6). This is not a single moderate effect, and reporting", "1025"),
("at any band -- every measurable", "at any band: every measurable", "1028"),
("band -- the opposite of what", "band, the opposite of what", "1085"),
("empirically falsifiable -- and partly\nfalsified -- refinement",
 "empirically falsifiable (and partly\nfalsified) refinement", "1167"),
("positive finding -- a real deployment did show a measured\nconsistency statistic correlating with something real about its own data --\nbut it was never",
 "positive finding (a real deployment did show a measured\nconsistency statistic correlating with something real about its own data),\nbut it was never", "1179"),
("from this repository -- a caveat repeated here", "from this repository, a caveat repeated here", "1188"),
("weaker form -- better-than-chance agreement, not monotonic\ndominance in every band -- is exactly why",
 "weaker form (better-than-chance agreement rather than monotonic\ndominance in every band) is exactly why", "1199"),
("hypothesis -- that ADS thresholds\nalone select the right mechanism -- is falsified",
 "hypothesis, that ADS thresholds\nalone select the right mechanism, is falsified", "1213"),
("precondition -- identical surface strings -- in a", "precondition, identical surface strings, in a", "1246"),
("observed -- the empirical winner is constant", "observed: the empirical winner is constant", "1254"),
("useless -- the accuracy-prediction finding", "useless: the accuracy-prediction finding", "1283"),
("exactly -- stated here as", "exactly, stated here as", "1323"),
("below 1.0 -- a real asymmetry", "below 1.0, a real asymmetry", "1328"),
("CLEAN-condition comparisons -- a sensitivity", "CLEAN-condition comparisons, a sensitivity", "1349"),
("compared -- not embedding-based retrieval, and not the shipped multi-tier\nproduction cascade.",
 "compared. Neither embedding-based retrieval nor the shipped multi-tier\nproduction cascade was tested.", "1360"),
("principled reason -- the synthetic product string carries\nno signal predictive of the true label -- and was not",
 "principled reason (the synthetic product string carries\nno signal predictive of the true label) and was not", "1362"),
("by this generator -- untested, not merely\nunfavorable.",
 "by this generator. That region is untested, not merely unfavorable.", "1395"),
("Section~5.5 -- retrieval's noise\ncost staying flat while rules' noise cost grows with realized ADS -- is",
 "Section~5.5 (retrieval's noise\ncost staying flat while rules' noise cost grows with realized ADS) is", "1430"),
("classification mechanisms -- exact-match rules or fuzzy retrieval -- should",
 "classification mechanisms, exact-match rules or fuzzy retrieval, should", "1473"),
("perform better -- named\nhere as a direction, not built or tested.",
 "perform better. We name it here as a direction, not as something built or\ntested.", "1483"),
]
for o,n,t in R: rep(o,n,t)
if E:
    print("\nFAILED:", E); sys.exit(1)
open('main.tex','w',encoding='utf-8',newline='').write(s)
print("\nAll", len(R), "edits applied.")
